### ISSUE TITLE
GeoJSON based conflation from a subset of OSM data

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/conflator#8]
**Is your feature request related to a problem? Please describe.**

- As discussed, we currently need the entire OSM postgres database to conflate against.
- This is great to possibly integrate into an microservice that sits alongside raw-data-api (which has the updated OSM database).
- But more realistically for tools like FMTM, we need to conflate against a small extract from OSM data.

**Describe the solution you'd like**

- The ideal scenario would be GeoJSON based conflation.
- Input: ODK data converted to GeoJSON, including all tag info as properties.
- Input: data extract geojson from raw-data-api, including tags as properties.
- Output: a single geojson of geometries, with conflated tags.
- Where the geometry or tag conflation has uncertainty, it would be good to flag with a confidence level, so the user can manually review the uncertain entries.

**Describe alternatives you've considered**

- Adding an OSM database alongside services like FMTM, but this would be significant data duplication.
- A future microservice to create a conflation API alongside raw-data-api.

**Comment by rsavoye** [comment]
conflator.py has been refactored to support this using and file from ODK and the data extract for FMTM.
